task:
  name: Ubuntu 14.04 build
  container:
    image: ubuntu:14.04
  install_script: apt-get update && apt-get install -y libgmp-dev g++
  compile_script: ./bootstrap.sh
  tests_script: ./perform_tests.et

task:
  name: Ubuntu 18.04 gcc build
  container:
    image: gcc:6
  env:
    CXX: g++
  install_script: apt update && apt install -y libgmp-dev
  compile_script: ./bootstrap.sh
  tests_script: ./perform_tests.et

task:
  name: Ubuntu 18.04 clang build
  container:
    image: teeks99/clang-ubuntu:3.4
  env:
    CXX: clang++-3.4
  install_script: apt update && apt install -y libgmp-dev
  compile_script: ./bootstrap.sh
  tests_script: ./perform_tests.et

task:
  name: FreeBSD 10.4 build
  freebsd_instance:
    image: freebsd-10-4-release-amd64
  install_script: pkg install -y gmp
  compile_script: ./bootstrap.sh
  tests_script: ./perform_tests.et

task:
  name: macOS Mojave build
  osx_instance:
    image: mojave-base
  install_script: brew install gmp
  compile_script: ./bootstrap.sh
  tests_script: ./perform_tests.et